#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/oneplus/lexus

PRODUCT_COPY_FILES += \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/3D-Lut_Center_P3.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/3D-Lut_Center_P3.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/3D-Lut_Center_sRGB.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/3D-Lut_Center_sRGB.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/3D-Lut_Enhance_P3.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/3D-Lut_Enhance_P3.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/3D-Lut_Enhance_sRGB.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/3D-Lut_Enhance_sRGB.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/3D-Lut_Stand_P3.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/3D-Lut_Stand_P3.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/3D-Lut_Stand_sRGB.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/3D-Lut_Stand_sRGB.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/3D-Lut_StandardMode_P3.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/3D-Lut_StandardMode_P3.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/3D-Lut_StandardMode_sRGB.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/3D-Lut_StandardMode_sRGB.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_1_100nit.odf:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_1_100nit.odf \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_1_2nit.odf:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_1_2nit.odf \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_1_max.odf:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_1_max.odf \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_2_100nit.odf:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_2_100nit.odf \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_2_2nit.odf:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_2_2nit.odf \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_2_max.odf:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_2_max.odf \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_Cinema_100nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_Cinema_100nits_pGC.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_Cinema_2nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_Cinema_2nits_pGC.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_Cinema_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_Cinema_pGC.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_EP3_100nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_EP3_100nits_pGC.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_EP3_2nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_EP3_2nits_pGC.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_EP3_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_EP3_pGC.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_EsRGB_100nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_EsRGB_100nits_pGC.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_EsRGB_2nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_EsRGB_2nits_pGC.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_EsRGB_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_EsRGB_pGC.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_HS:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_HS \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_LsRGB_100nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_LsRGB_100nits_pGC.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_LsRGB_2nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_LsRGB_2nits_pGC.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_LsRGB_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_LsRGB_pGC.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_Nature_100nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_Nature_100nits_pGC.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_Nature_2nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_Nature_2nits_pGC.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_Nature_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_Nature_pGC.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_Vivid_100nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_Vivid_100nits_pGC.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_Vivid_2nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_Vivid_2nits_pGC.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_Vivid_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA592_P_7_A0014_dsc_cmd_mode_panel_Vivid_pGC.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/AdjustValue:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AdjustValue \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/Lut3D_311:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/Lut3D_311 \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/Lut3D_312:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/Lut3D_312 \
    vendor/oneplus/lexus/proprietary/odm/etc/PanelChaplin/panelchaplin:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/panelchaplin \
    vendor/oneplus/lexus/proprietary/odm/etc/aac_richtap.config:$(TARGET_COPY_OUT_ODM)/etc/aac_richtap.config \
    vendor/oneplus/lexus/proprietary/odm/etc/acdbdata/Audio_Parameter_Version.txt:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Audio_Parameter_Version.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/acdbdata/FTM/acdb_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/FTM/acdb_cal.acdb \
    vendor/oneplus/lexus/proprietary/odm/etc/acdbdata/FTM/workspaceFileXml.qwsp:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/FTM/workspaceFileXml.qwsp \
    vendor/oneplus/lexus/proprietary/odm/etc/acdbdata/acdb_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/acdb_cal.acdb \
    vendor/oneplus/lexus/proprietary/odm/etc/acdbdata/up_ve_enpuv4_ha.eai:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/up_ve_enpuv4_ha.eai \
    vendor/oneplus/lexus/proprietary/odm/etc/acdbdata/up_ve_enpuv4_hh.eai:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/up_ve_enpuv4_hh.eai \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/CameraHWConfiguration.config:$(TARGET_COPY_OUT_ODM)/etc/camera/CameraHWConfiguration.config \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/CameraOemConfiguration.config:$(TARGET_COPY_OUT_ODM)/etc/camera/CameraOemConfiguration.config \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/M_FaceAttribute_RGB.model:$(TARGET_COPY_OUT_ODM)/etc/camera/M_FaceAttribute_RGB.model \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/Vega_Attribute_Face_RGB.model:$(TARGET_COPY_OUT_ODM)/etc/camera/Vega_Attribute_Face_RGB.model \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/Vega_Detect_FaceAnimal_Gray.model:$(TARGET_COPY_OUT_ODM)/etc/camera/Vega_Detect_FaceAnimal_Gray.model \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/Vega_Track_Animals_Gray.model:$(TARGET_COPY_OUT_ODM)/etc/camera/Vega_Track_Animals_Gray.model \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/aiboost_qnn_htp2.2.0_2468630351544828688.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/aiboost_qnn_htp2.2.0_2468630351544828688.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/aiboost_qnn_htp2.2.0_3404116395018271362.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/aiboost_qnn_htp2.2.0_3404116395018271362.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/ancsegbase/model.data:$(TARGET_COPY_OUT_ODM)/etc/camera/ancsegbase/model.data \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/camera_engmode.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/camera_engmode.xml \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/cfr_bin/CFR_lexusfront.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/cfr_bin/CFR_lexusfront.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/cfr_bin/CFR_lexusmain.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/cfr_bin/CFR_lexusmain.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/cfr_bin/CFR_lexuswide.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/cfr_bin/CFR_lexuswide.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/camera_third_party_feature_config.protobuf:$(TARGET_COPY_OUT_ODM)/etc/camera/config/camera_third_party_feature_config.protobuf \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/camera_unit_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/camera_unit_config \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/camera_unit_feature_config.protobuf:$(TARGET_COPY_OUT_ODM)/etc/camera/config/camera_unit_feature_config.protobuf \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/lexusfront:$(TARGET_COPY_OUT_ODM)/etc/camera/config/lexusfront \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/lexusmain:$(TARGET_COPY_OUT_ODM)/etc/camera/config/lexusmain \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/lexuswide:$(TARGET_COPY_OUT_ODM)/etc/camera/config/lexuswide \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/oplus_camera_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_config \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/pickref_params.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/config/pickref_params.xml \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/quick_visibility_white_list:$(TARGET_COPY_OUT_ODM)/etc/camera/config/quick_visibility_white_list \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/sr_params.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/config/sr_params.xml \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/video_beauty_default_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/video_beauty_default_config \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/distortionParams.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/distortionParams.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/dng/ColorMatrix1_lexusmain.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/ColorMatrix1_lexusmain.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/dng/ColorMatrix1_lexuswide.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/ColorMatrix1_lexuswide.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/dng/ColorMatrix2_lexusmain.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/ColorMatrix2_lexusmain.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/dng/ColorMatrix2_lexuswide.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/ColorMatrix2_lexuswide.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/dng/D28HUESATMap_lexusmain.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/D28HUESATMap_lexusmain.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/dng/D28HUESATMap_lexuswide.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/D28HUESATMap_lexuswide.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/dng/D65HUESATMap_lexusmain.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/D65HUESATMap_lexusmain.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/dng/D65HUESATMap_lexuswide.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/D65HUESATMap_lexuswide.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/dng/ToneCurve_lexusmain.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/ToneCurve_lexusmain.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/dng/ToneCurve_lexuswide.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/ToneCurve_lexuswide.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/dualcal_golden.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/dualcal_golden.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/eis_camera.vcfg:$(TARGET_COPY_OUT_ODM)/etc/camera/eis_camera.vcfg \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/fdc_cl.cache:$(TARGET_COPY_OUT_ODM)/etc/camera/fdc_cl.cache \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/fdc_lite_cl.cache:$(TARGET_COPY_OUT_ODM)/etc/camera/fdc_lite_cl.cache \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/fwk_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/fwk_config.json \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/gm_tcs3449_golden:$(TARGET_COPY_OUT_ODM)/etc/camera/gm_tcs3449_golden \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/main_inv_mapxy_33x25.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/main_inv_mapxy_33x25.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/main_mapxy_33x25.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/main_mapxy_33x25.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/media_profiles.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/media_profiles.xml \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/model_fdc.data:$(TARGET_COPY_OUT_ODM)/etc/camera/model_fdc.data \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/mvg_sat_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/mvg_sat_config.json \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/oplus_eis_camera.vcfg:$(TARGET_COPY_OUT_ODM)/etc/camera/oplus_eis_camera.vcfg \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/pfb_bin/PreCalVarBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreCalVarBinary.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/pfb_bin/PreHighPassBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreHighPassBinary.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/pfb_bin/PreHighPassPreBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreHighPassPreBinary.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/pfb_bin/PreHoriFilterBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreHoriFilterBinary.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/pfb_bin/PreMakeupBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreMakeupBinary.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/pfb_bin/PreMakeupMultiFaceBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreMakeupMultiFaceBinary.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/pfb_bin/PreMakeupSingleFaceBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreMakeupSingleFaceBinary.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/pfb_bin/PreMorphBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreMorphBinary.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/pfb_bin/PreOnlywhitenBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreOnlywhitenBinary.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/pfb_bin/PreSkintuneBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreSkintuneBinary.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/pfb_bin/PreSkintuneMRTBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreSkintuneMRTBinary.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/pfb_bin/PreSurfaceBlurBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreSurfaceBlurBinary.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/pfb_bin/PreVertFilterBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreVertFilterBinary.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/pfb_bin/PreVertSurBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreVertSurBinary.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/qnn_binary_3399573213435001949.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/qnn_binary_3399573213435001949.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/salient2_seg.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/salient2_seg.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/self_ois.ocfg:$(TARGET_COPY_OUT_ODM)/etc/camera/self_ois.ocfg \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/settings_fdc.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/settings_fdc.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/settings_fdc_lite.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/settings_fdc_lite.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/stereoParams.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/stereoParams.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/curve_lut_0:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/curve_lut_0 \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/curve_lut_1:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/curve_lut_1 \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/curve_lut_10:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/curve_lut_10 \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/curve_lut_2:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/curve_lut_2 \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/curve_lut_3:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/curve_lut_3 \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/curve_lut_4:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/curve_lut_4 \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/curve_lut_5:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/curve_lut_5 \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/curve_lut_6:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/curve_lut_6 \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/curve_lut_7:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/curve_lut_7 \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/curve_lut_8:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/curve_lut_8 \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/curve_lut_9:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/curve_lut_9 \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/list.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/list.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/s_curve_lut:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/s_curve_lut \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/tonemap_lut_0:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap_lut_0 \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/tonemap_lut_1:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap_lut_1 \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/tonemap_lut_10:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap_lut_10 \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/tonemap_lut_2:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap_lut_2 \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/tonemap_lut_3:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap_lut_3 \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/tonemap_lut_4:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap_lut_4 \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/tonemap_lut_5:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap_lut_5 \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/tonemap_lut_6:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap_lut_6 \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/tonemap_lut_7:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap_lut_7 \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/tonemap_lut_8:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap_lut_8 \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/tonemap/tonemap_lut_9:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap_lut_9 \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/wide_inv_padding_mapxy_33x25.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/wide_inv_padding_mapxy_33x25.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/wide_padding_mapxy_33x25.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/wide_padding_mapxy_33x25.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/display/qdcm_calib_data_AA592_P_7_A0014_dsc_cmd_mode_panel.json:$(TARGET_COPY_OUT_ODM)/etc/display/qdcm_calib_data_AA592_P_7_A0014_dsc_cmd_mode_panel.json \
    vendor/oneplus/lexus/proprietary/odm/etc/dolby/display/dolby_vision.cfg:$(TARGET_COPY_OUT_ODM)/etc/dolby/display/dolby_vision.cfg \
    vendor/oneplus/lexus/proprietary/odm/etc/dolby/dolby_vision.cfg:$(TARGET_COPY_OUT_ODM)/etc/dolby/dolby_vision.cfg \
    vendor/oneplus/lexus/proprietary/odm/etc/init/hw/init.oplus.display.rc:$(TARGET_COPY_OUT_ODM)/etc/init/hw/init.oplus.display.rc \
    vendor/oneplus/lexus/proprietary/odm/etc/init/init.camera_rfi.rc:$(TARGET_COPY_OUT_ODM)/etc/init/init.camera_rfi.rc \
    vendor/oneplus/lexus/proprietary/odm/etc/init/vendor.oplus.hardware.cammidasservice-V1-service.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor.oplus.hardware.cammidasservice-V1-service.rc \
    vendor/oneplus/lexus/proprietary/odm/etc/init/vendor.oplus.hardware.displaypanelfeature-service.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor.oplus.hardware.displaypanelfeature-service.rc \
    vendor/oneplus/lexus/proprietary/odm/etc/media_cliffs_v0/video_system_specs.json:$(TARGET_COPY_OUT_ODM)/etc/media_cliffs_v0/video_system_specs.json \
    vendor/oneplus/lexus/proprietary/odm/etc/media_codecs_dolby_vision.xml:$(TARGET_COPY_OUT_ODM)/etc/media_codecs_dolby_vision.xml \
    vendor/oneplus/lexus/proprietary/odm/etc/mixer_paths.xml:$(TARGET_COPY_OUT_ODM)/etc/mixer_paths.xml \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_2mic_calibration.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_2mic_calibration.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID10_MIC_VR.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID10_MIC_VR.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID10_MIC_VR.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID10_MIC_VR.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID11_HE.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID11_HE.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID11_HE.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID11_HE.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID12_HE_App1.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID12_HE_App1.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID12_HE_App1.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID12_HE_App1.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID13_HE_App2.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID13_HE_App2.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID13_HE_App2.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID13_HE_App2.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID14_HE_Cam.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID14_HE_Cam.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID14_HE_Cam.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID14_HE_Cam.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID15_HE_Conference.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID15_HE_Conference.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID15_HE_Conference.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID15_HE_Conference.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID16_HE_Fast.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID16_HE_Fast.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID16_HE_Fast.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID16_HE_Fast.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID17_HE_Interview.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID17_HE_Interview.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID17_HE_Interview.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID17_HE_Interview.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID18_HE_Unprocess.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID18_HE_Unprocess.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID18_HE_Unprocess.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID18_HE_Unprocess.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID19_HE_Voice.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID19_HE_Voice.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID19_HE_Voice.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID19_HE_Voice.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID1_MIC_normal.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID1_MIC_normal.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID1_MIC_normal.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID1_MIC_normal.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID20_HE_VR.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID20_HE_VR.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID20_HE_VR.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID20_HE_VR.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID21_HE_USB.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID21_HE_USB.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID21_HE_USB.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID21_HE_USB.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID22_HE_App1_USB.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID22_HE_App1_USB.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID22_HE_App1_USB.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID22_HE_App1_USB.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID23_BT_NORMAL.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID23_BT_NORMAL.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID23_BT_NORMAL.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID23_BT_NORMAL.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID24_BT_APP1.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID24_BT_APP1.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID24_BT_APP1.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID24_BT_APP1.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID25_ZOOM.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID25_ZOOM.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID25_ZOOM.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID25_ZOOM.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID26_Concert.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID26_Concert.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID26_Concert.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID26_Concert.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID2_MIC_App1.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID2_MIC_App1.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID2_MIC_App1.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID2_MIC_App1.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID3_MIC_App2.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID3_MIC_App2.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID3_MIC_App2.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID3_MIC_App2.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID4_MIC_Cam.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID4_MIC_Cam.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID4_MIC_Cam.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID4_MIC_Cam.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID5_MIC_Conference.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID5_MIC_Conference.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID5_MIC_Conference.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID5_MIC_Conference.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID6_MIC_Fast.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID6_MIC_Fast.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID6_MIC_Fast.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID6_MIC_Fast.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID7_MIC_Interview.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID7_MIC_Interview.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID7_MIC_Interview.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID7_MIC_Interview.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID8_MIC_Unprocess.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID8_MIC_Unprocess.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID8_MIC_Unprocess.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID8_MIC_Unprocess.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID99_Bypass.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID99_Bypass.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID99_Bypass.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID99_Bypass.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID9_MIC_Voice.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID9_MIC_Voice.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID9_MIC_Voice.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/2mic/oprec_audrec_parameter_2mic_ID9_MIC_Voice.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/oprec_audrec_params/oprec_audrec_config.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_audrec_config.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/resourcemanager.xml:$(TARGET_COPY_OUT_ODM)/etc/resourcemanager.xml \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/config/json_list:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/json_list \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/config/lexus_qrd_ois_system.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lexus_qrd_ois_system.json \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/config/lux_aod.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lux_aod.json \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/config/palawan_mtp_alsps.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_alsps.json \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/config/palawan_mtp_alsps_hw_tcs3720.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_alsps_hw_tcs3720.json \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/config/palawan_mtp_bmi26x.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_bmi26x.json \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/config/palawan_mtp_freefall.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_freefall.json \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/config/palawan_mtp_mmc56x3x.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_mmc56x3x.json \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/config/palawan_mtp_oplus_measurement.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_oplus_measurement.json \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/config/palawan_mtp_oplus_smart_prox.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_oplus_smart_prox.json \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/config/palawan_mtp_pocket.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_pocket.json \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/sensor_config.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/sensor_config.json \
    vendor/oneplus/lexus/proprietary/odm/etc/usecaseKvManager.xml:$(TARGET_COPY_OUT_ODM)/etc/usecaseKvManager.xml \
    vendor/oneplus/lexus/proprietary/odm/etc/wifi/qca6750/bdwlan.b0e:$(TARGET_COPY_OUT_ODM)/etc/wifi/qca6750/bdwlan.b0e \
    vendor/oneplus/lexus/proprietary/odm/etc/wifi/qca6750/bdwlan.b0i:$(TARGET_COPY_OUT_ODM)/etc/wifi/qca6750/bdwlan.b0i \
    vendor/oneplus/lexus/proprietary/odm/etc/wifi/qca6750/bdwlan.elf:$(TARGET_COPY_OUT_ODM)/etc/wifi/qca6750/bdwlan.elf \
    vendor/oneplus/lexus/proprietary/odm/etc/wifi/qca6750/regdb.bin:$(TARGET_COPY_OUT_ODM)/etc/wifi/qca6750/regdb.bin \
    vendor/oneplus/lexus/proprietary/odm/firmware/aw8697_haptic.bin:$(TARGET_COPY_OUT_ODM)/firmware/aw8697_haptic.bin \
    vendor/oneplus/lexus/proprietary/odm/firmware/aw8697_haptic_170.bin:$(TARGET_COPY_OUT_ODM)/firmware/aw8697_haptic_170.bin \
    vendor/oneplus/lexus/proprietary/odm/firmware/aw8697_haptic_170_soft.bin:$(TARGET_COPY_OUT_ODM)/firmware/aw8697_haptic_170_soft.bin \
    vendor/oneplus/lexus/proprietary/odm/firmware/fastchg/24881/charging_hyper_mode_config.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/24881/charging_hyper_mode_config.txt \
    vendor/oneplus/lexus/proprietary/odm/firmware/fastchg/bms_heating_config.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/bms_heating_config.txt \
    vendor/oneplus/lexus/proprietary/odm/firmware/fastchg/charging_thermal_config_default.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/charging_thermal_config_default.txt \
    vendor/oneplus/lexus/proprietary/odm/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_ODM)/firmware/tfa98xx.cnt \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/FW_S3910_TIANMA.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/FW_S3910_TIANMA.img \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/FW_S3910_TIANMA_FAE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/FW_S3910_TIANMA_FAE.img \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/FW_S3910_TIANMA_HBP.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/FW_S3910_TIANMA_HBP.img \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/FW_S3910_TIANMA_HBP_FAE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/FW_S3910_TIANMA_HBP_FAE.img \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/GloveDetect.tflite:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/GloveDetect.tflite \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/LIB_S3910_TIANMA_HBP_TS_ALGO.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/LIB_S3910_TIANMA_HBP_TS_ALGO.so \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/LIB_S3910_TIANMA_HBP_TS_ALGO_HWASAN.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/LIB_S3910_TIANMA_HBP_TS_ALGO_HWASAN.so \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/LIB_S3910_TIANMA_HBP_TS_HAL.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/LIB_S3910_TIANMA_HBP_TS_HAL.so \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/LIMIT_S3910_TIANMA_HBP.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/LIMIT_S3910_TIANMA_HBP.img \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/LIMIT_S3910_TIANMA_HBP_AGING.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/LIMIT_S3910_TIANMA_HBP_AGING.img \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/libIfp.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/libIfp.so \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/libaifilm.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/libaifilm.so \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/model.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/model.so \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/model.tflite:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/model.tflite \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/sys_edge_touch_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/sys_edge_touch_config.xml \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/sys_touch_algo_feature_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/sys_touch_algo_feature_config.xml \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/sys_touch_function_feature_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/sys_touch_function_feature_config.xml \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/sys_touch_scene_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/sys_touch_scene_config.xml \
    vendor/oneplus/lexus/proprietary/odm/firmware/uff_jv.b00:$(TARGET_COPY_OUT_ODM)/firmware/uff_jv.b00 \
    vendor/oneplus/lexus/proprietary/odm/firmware/uff_jv.b01:$(TARGET_COPY_OUT_ODM)/firmware/uff_jv.b01 \
    vendor/oneplus/lexus/proprietary/odm/firmware/uff_jv.b02:$(TARGET_COPY_OUT_ODM)/firmware/uff_jv.b02 \
    vendor/oneplus/lexus/proprietary/odm/firmware/uff_jv.b03:$(TARGET_COPY_OUT_ODM)/firmware/uff_jv.b03 \
    vendor/oneplus/lexus/proprietary/odm/firmware/uff_jv.b04:$(TARGET_COPY_OUT_ODM)/firmware/uff_jv.b04 \
    vendor/oneplus/lexus/proprietary/odm/firmware/uff_jv.b05:$(TARGET_COPY_OUT_ODM)/firmware/uff_jv.b05 \
    vendor/oneplus/lexus/proprietary/odm/firmware/uff_jv.b06:$(TARGET_COPY_OUT_ODM)/firmware/uff_jv.b06 \
    vendor/oneplus/lexus/proprietary/odm/firmware/uff_jv.b07:$(TARGET_COPY_OUT_ODM)/firmware/uff_jv.b07 \
    vendor/oneplus/lexus/proprietary/odm/firmware/uff_jv.b08:$(TARGET_COPY_OUT_ODM)/firmware/uff_jv.b08 \
    vendor/oneplus/lexus/proprietary/odm/firmware/uff_jv.mdt:$(TARGET_COPY_OUT_ODM)/firmware/uff_jv.mdt \
    vendor/oneplus/lexus/proprietary/odm/firmware/uff_spi.b00:$(TARGET_COPY_OUT_ODM)/firmware/uff_spi.b00 \
    vendor/oneplus/lexus/proprietary/odm/firmware/uff_spi.b01:$(TARGET_COPY_OUT_ODM)/firmware/uff_spi.b01 \
    vendor/oneplus/lexus/proprietary/odm/firmware/uff_spi.b02:$(TARGET_COPY_OUT_ODM)/firmware/uff_spi.b02 \
    vendor/oneplus/lexus/proprietary/odm/firmware/uff_spi.b03:$(TARGET_COPY_OUT_ODM)/firmware/uff_spi.b03 \
    vendor/oneplus/lexus/proprietary/odm/firmware/uff_spi.b04:$(TARGET_COPY_OUT_ODM)/firmware/uff_spi.b04 \
    vendor/oneplus/lexus/proprietary/odm/firmware/uff_spi.b05:$(TARGET_COPY_OUT_ODM)/firmware/uff_spi.b05 \
    vendor/oneplus/lexus/proprietary/odm/firmware/uff_spi.b06:$(TARGET_COPY_OUT_ODM)/firmware/uff_spi.b06 \
    vendor/oneplus/lexus/proprietary/odm/firmware/uff_spi.b07:$(TARGET_COPY_OUT_ODM)/firmware/uff_spi.b07 \
    vendor/oneplus/lexus/proprietary/odm/firmware/uff_spi.b08:$(TARGET_COPY_OUT_ODM)/firmware/uff_spi.b08 \
    vendor/oneplus/lexus/proprietary/odm/firmware/uff_spi.mdt:$(TARGET_COPY_OUT_ODM)/firmware/uff_spi.mdt \
    vendor/oneplus/lexus/proprietary/odm/firmware/ufs/MICRON-MT256GBEAZ4U31.bin:$(TARGET_COPY_OUT_ODM)/firmware/ufs/MICRON-MT256GBEAZ4U31.bin \
    vendor/oneplus/lexus/proprietary/odm/firmware/ufs/MICRON-MT512GAYAZ4U31.bin:$(TARGET_COPY_OUT_ODM)/firmware/ufs/MICRON-MT512GAYAZ4U31.bin \
    vendor/oneplus/lexus/proprietary/odm/firmware/ufs/SKhynix-HN8T15DEHKX075.bin:$(TARGET_COPY_OUT_ODM)/firmware/ufs/SKhynix-HN8T15DEHKX075.bin \
    vendor/oneplus/lexus/proprietary/odm/firmware/ufs/move_target_ufs_fw_to_oplusreserve1.sh:$(TARGET_COPY_OUT_ODM)/firmware/ufs/move_target_ufs_fw_to_oplusreserve1.sh \
    vendor/oneplus/lexus/proprietary/odm/firmware/ufs/ufs_version_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/ufs/ufs_version_config.xml \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/awb_parameter_default.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/awb_parameter_default.bin \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/awb_parameter_lexusfront.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/awb_parameter_lexusfront.bin \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/awb_parameter_lexusmain.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/awb_parameter_lexusmain.bin \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/awb_parameter_lexuswide.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/awb_parameter_lexuswide.bin \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/com.qti.sensormodule.lexusfront.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.lexusfront.bin \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/com.qti.sensormodule.lexusfront_DVT.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.lexusfront_DVT.bin \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/com.qti.sensormodule.lexusmain.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.lexusmain.bin \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/com.qti.sensormodule.lexuswide.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.lexuswide.bin \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.default.bin \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/com.qti.tuned.lexusfront.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.lexusfront.bin \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/com.qti.tuned.lexusmain.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.lexusmain.bin \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/com.qti.tuned.lexuswide.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.lexuswide.bin \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/libaecCustomParam_Cam0.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/libaecCustomParam_Cam0.bin \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/libaecCustomParam_Cam1.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/libaecCustomParam_Cam1.bin \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/libaecCustomParam_Cam2.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/libaecCustomParam_Cam2.bin \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/libafCustomParam_Cam0.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/libafCustomParam_Cam0.bin \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/libafCustomParam_Cam1.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/libafCustomParam_Cam1.bin \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/libafCustomParam_Cam2.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/libafCustomParam_Cam2.bin \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/libpdCustomParam_Cam0.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/libpdCustomParam_Cam0.bin \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/revision.txt:$(TARGET_COPY_OUT_ODM)/lib64/camera/revision.txt \
    vendor/oneplus/lexus/proprietary/odm/vendor/etc/wifi/WCNSS_qcom_cfg.ini:$(TARGET_COPY_OUT_ODM)/vendor/etc/wifi/WCNSS_qcom_cfg.ini \
    vendor/oneplus/lexus/proprietary/odm/vendor/firmware/alipay.b00:$(TARGET_COPY_OUT_ODM)/vendor/firmware/alipay.b00 \
    vendor/oneplus/lexus/proprietary/odm/vendor/firmware/alipay.b01:$(TARGET_COPY_OUT_ODM)/vendor/firmware/alipay.b01 \
    vendor/oneplus/lexus/proprietary/odm/vendor/firmware/alipay.b02:$(TARGET_COPY_OUT_ODM)/vendor/firmware/alipay.b02 \
    vendor/oneplus/lexus/proprietary/odm/vendor/firmware/alipay.b03:$(TARGET_COPY_OUT_ODM)/vendor/firmware/alipay.b03 \
    vendor/oneplus/lexus/proprietary/odm/vendor/firmware/alipay.b04:$(TARGET_COPY_OUT_ODM)/vendor/firmware/alipay.b04 \
    vendor/oneplus/lexus/proprietary/odm/vendor/firmware/alipay.b05:$(TARGET_COPY_OUT_ODM)/vendor/firmware/alipay.b05 \
    vendor/oneplus/lexus/proprietary/odm/vendor/firmware/alipay.b06:$(TARGET_COPY_OUT_ODM)/vendor/firmware/alipay.b06 \
    vendor/oneplus/lexus/proprietary/odm/vendor/firmware/alipay.b07:$(TARGET_COPY_OUT_ODM)/vendor/firmware/alipay.b07 \
    vendor/oneplus/lexus/proprietary/odm/vendor/firmware/alipay.b08:$(TARGET_COPY_OUT_ODM)/vendor/firmware/alipay.b08 \
    vendor/oneplus/lexus/proprietary/odm/vendor/firmware/alipay.mdt:$(TARGET_COPY_OUT_ODM)/vendor/firmware/alipay.mdt \
    vendor/oneplus/lexus/proprietary/odm/vendor/firmware/antdtx.b00:$(TARGET_COPY_OUT_ODM)/vendor/firmware/antdtx.b00 \
    vendor/oneplus/lexus/proprietary/odm/vendor/firmware/antdtx.b01:$(TARGET_COPY_OUT_ODM)/vendor/firmware/antdtx.b01 \
    vendor/oneplus/lexus/proprietary/odm/vendor/firmware/antdtx.b02:$(TARGET_COPY_OUT_ODM)/vendor/firmware/antdtx.b02 \
    vendor/oneplus/lexus/proprietary/odm/vendor/firmware/antdtx.b03:$(TARGET_COPY_OUT_ODM)/vendor/firmware/antdtx.b03 \
    vendor/oneplus/lexus/proprietary/odm/vendor/firmware/antdtx.b04:$(TARGET_COPY_OUT_ODM)/vendor/firmware/antdtx.b04 \
    vendor/oneplus/lexus/proprietary/odm/vendor/firmware/antdtx.b05:$(TARGET_COPY_OUT_ODM)/vendor/firmware/antdtx.b05 \
    vendor/oneplus/lexus/proprietary/odm/vendor/firmware/antdtx.b06:$(TARGET_COPY_OUT_ODM)/vendor/firmware/antdtx.b06 \
    vendor/oneplus/lexus/proprietary/odm/vendor/firmware/antdtx.b07:$(TARGET_COPY_OUT_ODM)/vendor/firmware/antdtx.b07 \
    vendor/oneplus/lexus/proprietary/odm/vendor/firmware/antdtx.b08:$(TARGET_COPY_OUT_ODM)/vendor/firmware/antdtx.b08 \
    vendor/oneplus/lexus/proprietary/odm/vendor/firmware/antdtx.mdt:$(TARGET_COPY_OUT_ODM)/vendor/firmware/antdtx.mdt \
    vendor/oneplus/lexus/proprietary/vendor/etc/2025-03-17_platform_RSA_SM8635_license_a6f644da-0221-4cb4-ab44-a7d8397b3d13.pfm:$(TARGET_COPY_OUT_VENDOR)/etc/2025-03-17_platform_RSA_SM8635_license_a6f644da-0221-4cb4-ab44-a7d8397b3d13.pfm \
    vendor/oneplus/lexus/proprietary/vendor/etc/clstc_config_library.xml:$(TARGET_COPY_OUT_VENDOR)/etc/clstc_config_library.xml \
    vendor/oneplus/lexus/proprietary/vendor/etc/display/DPU1010.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU1010.xml \
    vendor/oneplus/lexus/proprietary/vendor/etc/display/DPU1020.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU1020.xml \
    vendor/oneplus/lexus/proprietary/vendor/etc/display/DPU10__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU10__.xml \
    vendor/oneplus/lexus/proprietary/vendor/etc/display/DPU870.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU870.xml \
    vendor/oneplus/lexus/proprietary/vendor/etc/display/DPU9__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU9__.xml \
    vendor/oneplus/lexus/proprietary/vendor/etc/display/advanced_sf_offsets.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/advanced_sf_offsets.xml \
    vendor/oneplus/lexus/proprietary/vendor/etc/display/perf_hint_threshold.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/perf_hint_threshold.xml \
    vendor/oneplus/lexus/proprietary/vendor/etc/display/thermallevel_to_fps.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/thermallevel_to_fps.xml \
    vendor/oneplus/lexus/proprietary/vendor/etc/display_apollo_list_AA592_P_7_A0014_dsc_cmd_mode_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display_apollo_list_AA592_P_7_A0014_dsc_cmd_mode_panel.xml \
    vendor/oneplus/lexus/proprietary/vendor/etc/dolby_vision.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/dolby_vision.cfg \
    vendor/oneplus/lexus/proprietary/vendor/etc/init/feature_enabler_client.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/feature_enabler_client.rc \
    vendor/oneplus/lexus/proprietary/vendor/etc/init/init.qti.graphics.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.graphics.rc \
    vendor/oneplus/lexus/proprietary/vendor/etc/init/qdcmss.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qdcmss.rc \
    vendor/oneplus/lexus/proprietary/vendor/etc/init/vendor.qti.camera.provider-service_64.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.camera.provider-service_64.rc \
    vendor/oneplus/lexus/proprietary/vendor/etc/init/vendor.qti.hardware.display.color-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.display.color-service.rc \
    vendor/oneplus/lexus/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/oneplus/lexus/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/oneplus/lexus/proprietary/vendor/etc/ltm_config_AA592_P_7_A0014_dsc_cmd_mode_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ltm_config_AA592_P_7_A0014_dsc_cmd_mode_panel.xml \
    vendor/oneplus/lexus/proprietary/vendor/etc/oem_51_prj_OppoLTM8650_1689712162019.pfm:$(TARGET_COPY_OUT_VENDOR)/etc/oem_51_prj_OppoLTM8650_1689712162019.pfm \
    vendor/oneplus/lexus/proprietary/vendor/etc/snapdragon_color_libs_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/snapdragon_color_libs_config.xml \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b00 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b01 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b02 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b03 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b04 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b05 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b06 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b07 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b08 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b09 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b10 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b11 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b12 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b13 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b14 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b15 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b16 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b17 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b18 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b19 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b20 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.mbn \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.mdt \
    vendor/oneplus/lexus/proprietary/vendor/firmware/CAMERA_ICP_170.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP_170.elf \
    vendor/oneplus/lexus/proprietary/vendor/firmware/dpAP_full.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/dpAP_full.mbn \
    vendor/oneplus/lexus/proprietary/vendor/firmware/dpAP_mini.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/dpAP_mini.mbn \
    vendor/oneplus/lexus/proprietary/vendor/firmware/dpAP_modemssr.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/dpAP_modemssr.mbn \
    vendor/oneplus/lexus/proprietary/vendor/firmware/dpMSA.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/dpMSA.mbn \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass-lt.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b00 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass-lt.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b01 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass-lt.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b02 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass-lt.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b03 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass-lt.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b04 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass-lt.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b05 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass-lt.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b06 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass-lt.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b07 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass-lt.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b08 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass-lt.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b09 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass-lt.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b10 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass-lt.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b11 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass-lt.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b12 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass-lt.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b13 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass-lt.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b14 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass-lt.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b15 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass-lt.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b16 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass-lt.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b17 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass-lt.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b18 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass-lt.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b19 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass-lt.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.mbn \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass-lt.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.mdt \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b00 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b01 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b02 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b03 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b04 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b05 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b06 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b07 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b08 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b09 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b10 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b11 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b12 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b13 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b14 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b15 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b16 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b17 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b18 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b19 \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mbn \
    vendor/oneplus/lexus/proprietary/vendor/firmware/evass.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mdt \
    vendor/oneplus/lexus/proprietary/vendor/firmware/gen70900_aqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70900_aqe.fw \
    vendor/oneplus/lexus/proprietary/vendor/firmware/gen70900_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70900_sqe.fw \
    vendor/oneplus/lexus/proprietary/vendor/firmware/gen70900_zap.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70900_zap.mbn \
    vendor/oneplus/lexus/proprietary/vendor/firmware/gen71100_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gen71100_gmu.bin \
    vendor/oneplus/lexus/proprietary/vendor/firmware/gen71100_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen71100_sqe.fw \
    vendor/oneplus/lexus/proprietary/vendor/firmware/gen71100_zap.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/gen71100_zap.mbn \
    vendor/oneplus/lexus/proprietary/vendor/firmware/gmu_gen70900.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gmu_gen70900.bin \
    vendor/oneplus/lexus/proprietary/vendor/firmware/qps615_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/qps615_fw.bin \
    vendor/oneplus/lexus/proprietary/vendor/firmware/sn220u.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sn220u.bin \
    vendor/oneplus/lexus/proprietary/vendor/firmware/tof8801_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tof8801_firmware.bin \
    vendor/oneplus/lexus/proprietary/vendor/firmware/vpu20_2v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.mbn \
    vendor/oneplus/lexus/proprietary/vendor/firmware/vpu20_2v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v_unsigned.mbn \
    vendor/oneplus/lexus/proprietary/vendor/firmware/vpu20_4v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.mbn \
    vendor/oneplus/lexus/proprietary/vendor/firmware/vpu20_4v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v_unsigned.mbn \
    vendor/oneplus/lexus/proprietary/vendor/firmware/vpu30_2v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu30_2v.mbn \
    vendor/oneplus/lexus/proprietary/vendor/firmware/vpu30_2v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu30_2v_unsigned.mbn \
    vendor/oneplus/lexus/proprietary/vendor/firmware/vpu33_4v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu33_4v.mbn \
    vendor/oneplus/lexus/proprietary/vendor/firmware/vpu33_4v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu33_4v_unsigned.mbn \
    vendor/oneplus/lexus/proprietary/vendor/gpu/kbc/sequence_manifest.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/sequence_manifest.bin \
    vendor/oneplus/lexus/proprietary/vendor/gpu/kbc/unified_kbcs_64.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/unified_kbcs_64.bin \
    vendor/oneplus/lexus/proprietary/vendor/gpu/kbc/unified_ksqs.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/unified_ksqs.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b68v04s12n52.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b68v04s12n52.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b68v04s12n53.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b68v04s12n53.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n02.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n02.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n03.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n03.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n04.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n04.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n06.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n06.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n07.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n07.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n12.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n12.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n13.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n13.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n14.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n14.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n15.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n15.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n16.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n16.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n17.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n17.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n18.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n18.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n19.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n19.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n20.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n20.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n21.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n21.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n22.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n22.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n23.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n23.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n24.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n24.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n25.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n25.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n26.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n26.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n27.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n27.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n28.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n28.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n29.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n29.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n30.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n30.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n35.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n35.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n36.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n36.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n37.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n37.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n38.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n38.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n39.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n39.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n40.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n40.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n43.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n43.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n44.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n44.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n45.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n45.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n46.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n46.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n47.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n47.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n48.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n48.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n49.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n49.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n50.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n50.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n51.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n51.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n54.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n54.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n55.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n55.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n56.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n56.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n57.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n57.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n58.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n58.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n59.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n59.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n60.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n60.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n61.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n61.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n62.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n62.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n65.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n65.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n66.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n66.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm3b73v04s12n67.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n67.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a68v08s12n52.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a68v08s12n52.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a68v08s12n53.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a68v08s12n53.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n02.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n02.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n03.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n03.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n04.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n04.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n06.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n06.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n07.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n07.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n12.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n12.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n13.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n13.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n14.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n14.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n15.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n15.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n16.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n16.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n17.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n17.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n18.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n18.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n19.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n19.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n20.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n20.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n21.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n21.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n22.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n22.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n23.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n23.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n24.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n24.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n25.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n25.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n26.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n26.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n27.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n27.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n28.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n28.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n29.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n29.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n30.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n30.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n35.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n35.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n36.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n36.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n37.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n37.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n38.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n38.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n39.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n39.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n40.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n40.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n43.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n43.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n44.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n44.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n45.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n45.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n46.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n46.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n47.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n47.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n48.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n48.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n49.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n49.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n50.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n50.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n51.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n51.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n54.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n54.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n55.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n55.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n56.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n56.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n57.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n57.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n58.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n58.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n59.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n59.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n60.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n60.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n61.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n61.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/bm4a73v08s12n62.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n62.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/camera/arcsoft_calibration_uw.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/arcsoft_calibration_uw.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/camera/arcsoft_calibration_wt.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/arcsoft_calibration_wt.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/camera/arcsoft_dc_calibration_t.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/arcsoft_dc_calibration_t.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/camera/arcsoft_dc_calibration_u.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/arcsoft_dc_calibration_u.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/camera/arcsoft_dc_calibration_w.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/arcsoft_dc_calibration_w.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/camera/bitmlconfig.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/bitmlconfig.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/camera/bitmlconfig_sm8635.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/bitmlconfig_sm8635.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/camera/camxfl115indices.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/camxfl115indices.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/camera/camxfl300v1indices.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/camxfl300v1indices.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/camera/camxfl300v2indices.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/camxfl300v2indices.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/camera/camxflcustom300indices.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/camxflcustom300indices.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/camera/fdconfigsecure.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigsecure.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideolite.bin \
    vendor/oneplus/lexus/proprietary/vendor/lib64/libpnc_cl_program.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/libpnc_cl_program.bin

PRODUCT_PACKAGES += \
    com.qti.eeprom.gt24p128c2csli_imx766 \
    com.qti.eeprom.gt24p128e2csli_s5kjn1 \
    com.qti.eeprom.irs2381c_polar \
    com.qti.eeprom.truly_cmb433 \
    com.qti.ois.bu63169gwz \
    com.qti.ois.dw9784 \
    com.arcsoft.node.smooth_transition \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.hwcfg.bps \
    com.qti.hwcfg.ife \
    com.qti.hwcfg.ipe \
    com.qti.hwcfg.tfe \
    com.qti.node.afbfusion \
    com.qti.node.aon \
    com.qti.node.customhwnode \
    com.qti.node.depth \
    com.qti.node.depthprovider \
    com.qti.node.dewarp \
    com.qti.node.dummydepth \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.evadepth \
    com.qti.node.evs \
    com.qti.node.fcv \
    com.qti.node.formatconversion \
    com.qti.node.gme \
    com.qti.node.gpu \
    com.qti.node.gyrornn \
    com.qti.node.hdr10pgen \
    com.qti.node.hdr10phist \
    com.qti.node.itofpreprocess \
    com.qti.node.memcpy \
    com.qti.node.ml \
    com.qti.node.mlinference \
    com.qti.node.muxer \
    com.qti.node.remosaic \
    com.qti.node.seg \
    com.qti.node.stich \
    com.qti.node.swaidenoiser \
    com.qti.node.swbestats \
    com.qti.node.swcac \
    com.qti.node.swec \
    com.qti.node.swfusion \
    com.qti.node.swhme \
    com.qti.node.swlsc \
    com.qti.node.swmctf \
    com.qti.node.swpdpc \
    com.qti.node.swpnc \
    com.qti.node.swpreprocess \
    com.qti.node.swregistration \
    com.qti.node.swvrt \
    com.qti.stats.aec \
    com.qti.stats.aecwrapper \
    com.qti.stats.aecxcore \
    com.qti.stats.af \
    com.qti.stats.afc \
    com.qti.stats.afd \
    com.qti.stats.afwrapper \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbr \
    com.qti.stats.awbwrapper \
    com.qti.stats.cnndriver \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.localhistogram \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.roimixer \
    com.qti.stats.roimixerlib \
    com.qti.stats.statsgenerator \
    com.qti.stats.tracker \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    libcamxevainterface \
    libdepthmapwrapper \
    libdepthmapwrapper_itof \
    libdepthmapwrapper_secure \
    camx.device-impl \
    camx.provider-impl \
    com.qti.camx.chiiqutils \
    com.qti.chiusecaseselector \
    com.qti.feature2.afbrckt \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.derivedoffline \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs.sm8650 \
    com.qti.feature2.hdr \
    com.qti.feature2.mcreprocrt \
    com.qti.feature2.memcpy \
    com.qti.feature2.metadataserializer \
    com.qti.feature2.mfsr \
    com.qti.feature2.ml \
    com.qti.feature2.mux \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.realtimeserializer \
    com.qti.feature2.rt \
    com.qti.feature2.rtmcx \
    com.qti.feature2.serializer \
    com.qti.feature2.statsregeneration \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    com.qti.qseeaon \
    com.qti.qseeutils \
    com.qti.settings.sm8650 \
    com.qti.stats.common \
    com.qualcomm.mcx.distortionmapper \
    com.qualcomm.mcx.linearmapper \
    com.qualcomm.mcx.nonlinearmapper \
    com.qualcomm.mcx.policy.mfl \
    com.qualcomm.qti.mcx.usecase.extension \
    camera.qcom.sm8650 \
    camera.qcom \
    com.qti.chi.offline \
    com.qti.chi.override \
    libGCore4Cell_32E2 \
    libPanelChaplin_vendor \
    libRGBC \
    libSonyIMX471RmscLibrary \
    libaacvibrator \
    libaidenoiser \
    libaidenoiserv2 \
    libarcsoft_triple_sat \
    libbacklight-calib \
    libbitmlengine \
    libbitmlenginev2 \
    libcamerapostproc \
    libcamxcommonutils \
    libcamxexternalformatutils \
    libcamxfdengine \
    libcamxhwnodecontext \
    libcamxifestriping \
    libcamximageformatutils \
    libcamxjson \
    libcamxncsdatafactory \
    libcamxqsatalgo \
    libcamxsettingsmanager \
    libcamxstatscore \
    libcamxswispiqmodule \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libchifeature2 \
    libchilog \
    libclstc_algorithm_adapter \
    libclstc_gcp_adapter \
    libclstc_tm \
    libcolor-default \
    libcom.qti.chinodeutils \
    libcommonchiutils \
    libcwb_client_vendor \
    libcwb_qcom_aidl \
    libdepthcomputation \
    libdigital-dimming \
    libdisp-aba \
    libdisplayconfig.qti \
    libdisplayqos \
    libdisplayskuutils \
    libdpp_manager \
    libdpps \
    libdtlm \
    libdualcam_optical_zoom_control \
    libdualcam_video_optical_zoom \
    libeepromcutter \
    libfeutils \
    libgame_enhance \
    libhdr10plus \
    libhdr_backlight_adapter \
    libhdr_stub \
    libhdr_tm \
    libhdrdynamic \
    libhdrdynamicootf \
    libhdrvivid \
    libhistogram \
    libhme \
    libhwconfigurationutil_vendor \
    libhwcsensor \
    libintervmipc \
    libipebpsstriping \
    libipebpsstriping170 \
    libipebpsstriping480 \
    libisphwsetting \
    libjni_aidenoiserutilv2 \
    libjni_imageutil \
    libjpege \
    libmctfengine_stub \
    libmemutils \
    libmfGhostDetection \
    libmfec \
    libmidasserviceintf \
    libmidasserviceintf_aidl \
    libmmcamera_bestats \
    libmmcamera_cac \
    libmmcamera_lscv35 \
    libmmcamera_mfnr \
    libmmcamera_mfnr_t4 \
    libmmcamera_pdpc \
    libmmcamera_pnc \
    libopencv \
    libopencv3a \
    libopestriping \
    libpwirisfeature_vendor \
    libpwirishal \
    libpwirishalwrapper_vendor \
    libqdcm-algo \
    libqdcm-json-mode-parser \
    libqdcm-mode-parser \
    libqdutils \
    libqll \
    libqll10 \
    libqllengine \
    libqrtrclient \
    libqseed3 \
    libqshcamera \
    librcmask \
    libsdedrm \
    libsdm-color \
    libsdm-colormgr-algo \
    libsdm-disp-vndapis \
    libsdmcore \
    libsdmdal \
    libsdmextension \
    libsdmutils \
    libsfeShiftExtrapolation \
    libsgutils2 \
    libsnapdragoncolor-manager \
    libsnapdragoncolor-qdcm \
    libspectre \
    libswregistrationalgo \
    libtestutils \
    libtfestriping \
    libtinyxml2_1 \
    libtriplecam_optical_zoom_control \
    libtriplecam_video_optical_zoom \
    libubifocus \
    libvideoml \
    libvmfilexfer \
    sensors.qsh \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.color@1.3 \
    vendor.display.color@1.4 \
    vendor.display.color@1.5 \
    vendor.display.postproc@1.0 \
    vendor.oplus.hardware.camera.aon-service-impl \
    vendor.oplus.hardware.cammidasservice@1.0 \
    vendor.pixelworks.hardware.display-V2-ndk \
    vendor.pixelworks.hardware.display@1.0_vendor \
    vendor.pixelworks.hardware.display@1.1_vendor \
    vendor.pixelworks.hardware.display@1.2_vendor \
    vendor.pixelworks.hardware.feature-V1-ndk \
    vendor.pixelworks.hardware.feature@1.0_vendor \
    vendor.pixelworks.hardware.feature@1.1_vendor \
    vendor.qti.hardware.camera.aon-service-impl \
    vendor.qti.hardware.camera.offlinecamera-service-impl \
    vendor.qti.hardware.camera.postproc@1.0-service-impl \
    vendor.qti.hardware.qdutils_disp@1.0 \
    libQnnHtpV73Skel.signed.aiframe \
    libQnnHtpV73Skel.unsigned.aiframe \
    libQnnHtp.aiframe \
    libQnnHtpPrepare.aiframe \
    libQnnHtpV73Stub.aiframe \
    libQnnSystem.aiframe \
    libaiboost_qnn_external_delegate \
    libqcom_llm \
    libtransformer_lite \
    com.qti.sensor.lexusfront \
    com.qti.sensor.lexusmain \
    com.qti.sensor.lexuswide \
    com.oplus.node.mvgsat \
    com.oplus.node.preview \
    com.oplus.node.sstabdefer \
    com.oplus.node.sstabgme \
    com.oplus.node.sstabphoto \
    com.oplus.node.sstabrealt \
    camera.oemlayer \
    libAF \
    libAncSegmentSdk \
    libCOppLceTonemapAPI \
    libCS \
    libEIS \
    libFDClite \
    libFaceDistortionCorrection \
    libHIS \
    libODNN \
    libOGLManager \
    libOplusPDCore \
    libOpo_awb \
    libPanelChaplin \
    libPlatformValidatorShared \
    libQnnCpu \
    libQnnGpu \
    libQnnHtp \
    libQnnHtpPrepare \
    libQnnHtpV73CalculatorStub \
    libQnnHtpV73Stub \
    libQnnSaver \
    libQnnSystem \
    libSNPE \
    libUpScale \
    libVDBayerHDR \
    libVDBlurless \
    libVDExternal \
    libVDSuperPhotoAPI \
    libYTCommon \
    lib_geofencing \
    lib_rectify \
    libaecCustom \
    libaecCustomParamParser \
    libafCustomParamParser \
    libaiboost \
    libaiboost_llm \
    libaiboost_qnn_external_delegate_te \
    libaiboost_te \
    libaisal \
    libalCFR \
    libalog \
    libalogencrypt \
    libancbase_rt_fusion \
    libancbase_segbase \
    libancbase_segment \
    libancbase_segmulti \
    libapsexif \
    libapsjpeg \
    libapspng \
    libapsultrahdr \
    libapsyuv \
    libarc.ion \
    libarcsoft_videoautozoom \
    libc++_shared \
    libcalculator \
    libcalculator_htp \
    libcreatebin \
    libcvface_api \
    libdisplayaidlapis \
    libdolbyclstc \
    libdpaservice \
    libexif-jpeg-aps \
    libextendfile \
    libextensionlayer \
    libfovctrl \
    libhwconfigurationutil \
    libml_util \
    libmpbase \
    libmvgcommon \
    libocce3a \
    liboemconfigurationutil \
    liboprec_audrec \
    liboprec_audrec_wrapper \
    libpdCustomParamParser \
    libpngwrapper \
    libpwirisfeature \
    libpwirishalwrapper \
    libqsh.utils \
    libremosaic_wrapper \
    libsat \
    libsaveshaderbin \
    libsharebuffer \
    libsharebuffer_impl \
    libstfd_mobile_api \
    libtensorflowlite_oplus \
    libtfa98xx \
    libthirdcapability \
    libtrace \
    libvega_common \
    libvega_face \
    libwrapper_te \
    libyuv2 \
    libyuvwrapper \
    libzlib \
    vendor.oplus.hardware.camera_rfi-V1-service-impl \
    vendor.oplus.hardware.sendextcamcmd-V1-service-impl \
    vendor.pixelworks.hardware.display@1.0 \
    vendor.pixelworks.hardware.display@1.1 \
    vendor.pixelworks.hardware.display@1.2 \
    vendor.pixelworks.hardware.feature@1.0 \
    vendor.pixelworks.hardware.feature@1.1 \
    odm_lib_rfsa_adsp_libCalculator_skel_so \
    odm_lib_rfsa_adsp_libQnnHtpV73_so \
    odm_lib_rfsa_adsp_libQnnHtpV73Skel_so \
    odm_lib_rfsa_adsp_libQnnSaver_so \
    odm_lib_rfsa_adsp_libSnpeHtpV73Skel_so \
    odm_lib_rfsa_adsp_libSuperRawPost_skel_so \
    odm_lib_rfsa_adsp_libaisr_skel_so \
    odm_lib_rfsa_adsp_libarc_gk_pt_hvx_skel_so \
    odm_lib_rfsa_adsp_libarc_htp_driver_skel_so \
    odm_lib_rfsa_adsp_libcalculator_skel_so \
    odm_lib_rfsa_adsp_libhvxFaceBeautyPre_skel_so \
    odm_lib_rfsa_adsp_libktveffect_so \
    odm_lib_rfsa_adsp_libtfadsp_sb5_5_rx_so \
    odm_lib_rfsa_adsp_libtfadsp_sb5_5_tx_so \
    odm_lib_rfsa_adsp_libvdblurless_5_0_2_skel_so \
    odm_lib_rfsa_adsp_libvdsuperphoto_skel_so \
    vendor.qti.camera.aon-impl.xml \
    vendor.qti.camera.offlinecamera-impl.xml \
    vendor.qti.camera.postproc-impl.xml \
    vendor.qti.camera.provider.xml \
    manifest_oplus_camera_rfi.xml \
    manifest_oplus_cammidasservice_aidl.xml \
    manifest_oplus_cwb_aidl.xml \
    manifest_oplus_displaypanelfeature_aidl.xml \
    manifest_oplus_sendextcamcmd.xml \
    vintf_manifext_aidl_panelchaplin.xml \
    feature_enabler_client \
    vendor.qti.camera.provider-service_64 \
    vendor.qti.hardware.display.color-service \
    vendor.qti.hardware.display.composer-service \
    init.qti.graphics \
    ppd \
    qdcmss \
    cwb_utils_aidl \
    vendor.oplus.hardware.cammidasservice-V1-service \
    vendor.oplus.hardware.displaypanelfeature-service
